services:

  postgres:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  server:
    build:
      context: .
      target: production
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./:/app
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

  health:
    build:
      context: .
      dockerfile: cmd/health/Dockerfile
      target: production
    restart: unless-stopped
    ports:
      - "50001:50001"
    env_file:
      - .env
    depends_on:
      - server
    volumes:
      - ./:/app
    networks:
      - backend

volumes:
  db-data:
    
networks:
  backend: