services:

  server:
    build:
      context: .
      target: development
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./:/app
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

  postgres:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fihub
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  db-data:
    
networks:
  backend: