services:
  server:
    build: .
    restart: unless-stopped
    ports:
      - "${GO_PORT}:${GO_PORT}"
    depends_on:
      - postgres
    volumes:
      - ./:/app
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
  postgres:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  db-data:
    
networks:
  backend: