services:
  server:
    build: .
    restart: unless-stopped
    ports:
      - "${GO_PORT}:${GO_PORT}"
    depends_on:
      - db
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: unless-stopped
    networks:
      - backend

networks:
  backend: