// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/security.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Permission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_proto_security_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{0}
}

func (x *Permission) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Permission) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Permission) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Permission) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreatePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionRequest) Reset() {
	*x = CreatePermissionRequest{}
	mi := &file_proto_security_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionRequest) ProtoMessage() {}

func (x *CreatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionRequest.ProtoReflect.Descriptor instead.
func (*CreatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePermissionRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CreatePermissionRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *CreatePermissionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreatePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permission    *Permission            `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionResponse) Reset() {
	*x = CreatePermissionResponse{}
	mi := &file_proto_security_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionResponse) ProtoMessage() {}

func (x *CreatePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionResponse.ProtoReflect.Descriptor instead.
func (*CreatePermissionResponse) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePermissionResponse) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type GetPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionRequest) Reset() {
	*x = GetPermissionRequest{}
	mi := &file_proto_security_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionRequest) ProtoMessage() {}

func (x *GetPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionRequest.ProtoReflect.Descriptor instead.
func (*GetPermissionRequest) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{3}
}

func (x *GetPermissionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permission    *Permission            `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionResponse) Reset() {
	*x = GetPermissionResponse{}
	mi := &file_proto_security_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionResponse) ProtoMessage() {}

func (x *GetPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionResponse.ProtoReflect.Descriptor instead.
func (*GetPermissionResponse) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{4}
}

func (x *GetPermissionResponse) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type UpdatePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermissionRequest) Reset() {
	*x = UpdatePermissionRequest{}
	mi := &file_proto_security_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionRequest) ProtoMessage() {}

func (x *UpdatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionRequest.ProtoReflect.Descriptor instead.
func (*UpdatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePermissionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePermissionRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *UpdatePermissionRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *UpdatePermissionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdatePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permission    *Permission            `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermissionResponse) Reset() {
	*x = UpdatePermissionResponse{}
	mi := &file_proto_security_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionResponse) ProtoMessage() {}

func (x *UpdatePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionResponse.ProtoReflect.Descriptor instead.
func (*UpdatePermissionResponse) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePermissionResponse) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type DeletePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionRequest) Reset() {
	*x = DeletePermissionRequest{}
	mi := &file_proto_security_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionRequest) ProtoMessage() {}

func (x *DeletePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionRequest.ProtoReflect.Descriptor instead.
func (*DeletePermissionRequest) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePermissionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionResponse) Reset() {
	*x = DeletePermissionResponse{}
	mi := &file_proto_security_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionResponse) ProtoMessage() {}

func (x *DeletePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionResponse.ProtoReflect.Descriptor instead.
func (*DeletePermissionResponse) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePermissionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsRequest) Reset() {
	*x = ListPermissionsRequest{}
	mi := &file_proto_security_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsRequest) ProtoMessage() {}

func (x *ListPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsRequest.ProtoReflect.Descriptor instead.
func (*ListPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{9}
}

type ListPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []*Permission          `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsResponse) Reset() {
	*x = ListPermissionsResponse{}
	mi := &file_proto_security_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsResponse) ProtoMessage() {}

func (x *ListPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsResponse.ProtoReflect.Descriptor instead.
func (*ListPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{10}
}

func (x *ListPermissionsResponse) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_proto_security_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{11}
}

func (x *Role) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RoleWithPermissions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *Role                  `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Permissions   []*Permission          `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleWithPermissions) Reset() {
	*x = RoleWithPermissions{}
	mi := &file_proto_security_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleWithPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleWithPermissions) ProtoMessage() {}

func (x *RoleWithPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleWithPermissions.ProtoReflect.Descriptor instead.
func (*RoleWithPermissions) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{12}
}

func (x *RoleWithPermissions) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *RoleWithPermissions) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Permissions   []string               `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_proto_security_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{13}
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type CreateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *RoleWithPermissions   `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleResponse) Reset() {
	*x = CreateRoleResponse{}
	mi := &file_proto_security_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleResponse) ProtoMessage() {}

func (x *CreateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleResponse.ProtoReflect.Descriptor instead.
func (*CreateRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{14}
}

func (x *CreateRoleResponse) GetRole() *RoleWithPermissions {
	if x != nil {
		return x.Role
	}
	return nil
}

type GetRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_proto_security_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequest.ProtoReflect.Descriptor instead.
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{15}
}

func (x *GetRoleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *RoleWithPermissions   `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleResponse) Reset() {
	*x = GetRoleResponse{}
	mi := &file_proto_security_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleResponse) ProtoMessage() {}

func (x *GetRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleResponse.ProtoReflect.Descriptor instead.
func (*GetRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{16}
}

func (x *GetRoleResponse) GetRole() *RoleWithPermissions {
	if x != nil {
		return x.Role
	}
	return nil
}

type UpdateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Permissions   []string               `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_proto_security_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateRoleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRoleRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type UpdateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *RoleWithPermissions   `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleResponse) Reset() {
	*x = UpdateRoleResponse{}
	mi := &file_proto_security_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleResponse) ProtoMessage() {}

func (x *UpdateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateRoleResponse) GetRole() *RoleWithPermissions {
	if x != nil {
		return x.Role
	}
	return nil
}

type DeleteRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_proto_security_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteRoleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleResponse) Reset() {
	*x = DeleteRoleResponse{}
	mi := &file_proto_security_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleResponse) ProtoMessage() {}

func (x *DeleteRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteRoleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_proto_security_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{21}
}

type ListRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*RoleWithPermissions `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesResponse) Reset() {
	*x = ListRolesResponse{}
	mi := &file_proto_security_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse) ProtoMessage() {}

func (x *ListRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesResponse.ProtoReflect.Descriptor instead.
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{22}
}

func (x *ListRolesResponse) GetRoles() []*RoleWithPermissions {
	if x != nil {
		return x.Roles
	}
	return nil
}

type ListRolePermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolePermissionsRequest) Reset() {
	*x = ListRolePermissionsRequest{}
	mi := &file_proto_security_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolePermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolePermissionsRequest) ProtoMessage() {}

func (x *ListRolePermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolePermissionsRequest.ProtoReflect.Descriptor instead.
func (*ListRolePermissionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{23}
}

func (x *ListRolePermissionsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListRolePermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []*Permission          `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolePermissionsResponse) Reset() {
	*x = ListRolePermissionsResponse{}
	mi := &file_proto_security_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolePermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolePermissionsResponse) ProtoMessage() {}

func (x *ListRolePermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolePermissionsResponse.ProtoReflect.Descriptor instead.
func (*ListRolePermissionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{24}
}

func (x *ListRolePermissionsResponse) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type SetRolePermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Permissions   []string               `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRolePermissionsRequest) Reset() {
	*x = SetRolePermissionsRequest{}
	mi := &file_proto_security_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRolePermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRolePermissionsRequest) ProtoMessage() {}

func (x *SetRolePermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRolePermissionsRequest.ProtoReflect.Descriptor instead.
func (*SetRolePermissionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{25}
}

func (x *SetRolePermissionsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetRolePermissionsRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type SetRolePermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRolePermissionsResponse) Reset() {
	*x = SetRolePermissionsResponse{}
	mi := &file_proto_security_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRolePermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRolePermissionsResponse) ProtoMessage() {}

func (x *SetRolePermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRolePermissionsResponse.ProtoReflect.Descriptor instead.
func (*SetRolePermissionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{26}
}

func (x *SetRolePermissionsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AddUsersToRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	UserIds       []string               `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUsersToRoleRequest) Reset() {
	*x = AddUsersToRoleRequest{}
	mi := &file_proto_security_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUsersToRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUsersToRoleRequest) ProtoMessage() {}

func (x *AddUsersToRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUsersToRoleRequest.ProtoReflect.Descriptor instead.
func (*AddUsersToRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{27}
}

func (x *AddUsersToRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *AddUsersToRoleRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type AddUsersToRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUsersToRoleResponse) Reset() {
	*x = AddUsersToRoleResponse{}
	mi := &file_proto_security_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUsersToRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUsersToRoleResponse) ProtoMessage() {}

func (x *AddUsersToRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUsersToRoleResponse.ProtoReflect.Descriptor instead.
func (*AddUsersToRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{28}
}

func (x *AddUsersToRoleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RemoveUsersFromRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	UserIds       []string               `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUsersFromRoleRequest) Reset() {
	*x = RemoveUsersFromRoleRequest{}
	mi := &file_proto_security_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUsersFromRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUsersFromRoleRequest) ProtoMessage() {}

func (x *RemoveUsersFromRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUsersFromRoleRequest.ProtoReflect.Descriptor instead.
func (*RemoveUsersFromRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{29}
}

func (x *RemoveUsersFromRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *RemoveUsersFromRoleRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type RemoveUsersFromRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUsersFromRoleResponse) Reset() {
	*x = RemoveUsersFromRoleResponse{}
	mi := &file_proto_security_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUsersFromRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUsersFromRoleResponse) ProtoMessage() {}

func (x *RemoveUsersFromRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUsersFromRoleResponse.ProtoReflect.Descriptor instead.
func (*RemoveUsersFromRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{30}
}

func (x *RemoveUsersFromRoleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListUsersForRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersForRoleRequest) Reset() {
	*x = ListUsersForRoleRequest{}
	mi := &file_proto_security_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersForRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersForRoleRequest) ProtoMessage() {}

func (x *ListUsersForRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersForRoleRequest.ProtoReflect.Descriptor instead.
func (*ListUsersForRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{31}
}

func (x *ListUsersForRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

type ListUsersForRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersForRoleResponse) Reset() {
	*x = ListUsersForRoleResponse{}
	mi := &file_proto_security_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersForRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersForRoleResponse) ProtoMessage() {}

func (x *ListUsersForRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersForRoleResponse.ProtoReflect.Descriptor instead.
func (*ListUsersForRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{32}
}

func (x *ListUsersForRoleResponse) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type SetRolesForUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleIds       []string               `protobuf:"bytes,2,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRolesForUserRequest) Reset() {
	*x = SetRolesForUserRequest{}
	mi := &file_proto_security_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRolesForUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRolesForUserRequest) ProtoMessage() {}

func (x *SetRolesForUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRolesForUserRequest.ProtoReflect.Descriptor instead.
func (*SetRolesForUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{33}
}

func (x *SetRolesForUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetRolesForUserRequest) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

type SetRolesForUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRolesForUserResponse) Reset() {
	*x = SetRolesForUserResponse{}
	mi := &file_proto_security_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRolesForUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRolesForUserResponse) ProtoMessage() {}

func (x *SetRolesForUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRolesForUserResponse.ProtoReflect.Descriptor instead.
func (*SetRolesForUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{34}
}

func (x *SetRolesForUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListRolesForUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesForUserRequest) Reset() {
	*x = ListRolesForUserRequest{}
	mi := &file_proto_security_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesForUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesForUserRequest) ProtoMessage() {}

func (x *ListRolesForUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesForUserRequest.ProtoReflect.Descriptor instead.
func (*ListRolesForUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{35}
}

func (x *ListRolesForUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListRolesForUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*Role                `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesForUserResponse) Reset() {
	*x = ListRolesForUserResponse{}
	mi := &file_proto_security_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesForUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesForUserResponse) ProtoMessage() {}

func (x *ListRolesForUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesForUserResponse.ProtoReflect.Descriptor instead.
func (*ListRolesForUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{36}
}

func (x *ListRolesForUserResponse) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type ListRolesWithPermissionsForUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesWithPermissionsForUserRequest) Reset() {
	*x = ListRolesWithPermissionsForUserRequest{}
	mi := &file_proto_security_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesWithPermissionsForUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesWithPermissionsForUserRequest) ProtoMessage() {}

func (x *ListRolesWithPermissionsForUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesWithPermissionsForUserRequest.ProtoReflect.Descriptor instead.
func (*ListRolesWithPermissionsForUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{37}
}

func (x *ListRolesWithPermissionsForUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListRolesWithPermissionsForUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*RoleWithPermissions `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesWithPermissionsForUserResponse) Reset() {
	*x = ListRolesWithPermissionsForUserResponse{}
	mi := &file_proto_security_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesWithPermissionsForUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesWithPermissionsForUserResponse) ProtoMessage() {}

func (x *ListRolesWithPermissionsForUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesWithPermissionsForUserResponse.ProtoReflect.Descriptor instead.
func (*ListRolesWithPermissionsForUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{38}
}

func (x *ListRolesWithPermissionsForUserResponse) GetRoles() []*RoleWithPermissions {
	if x != nil {
		return x.Roles
	}
	return nil
}

type UserWithRoles struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Roles         []*Role                `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserWithRoles) Reset() {
	*x = UserWithRoles{}
	mi := &file_proto_security_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserWithRoles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserWithRoles) ProtoMessage() {}

func (x *UserWithRoles) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserWithRoles.ProtoReflect.Descriptor instead.
func (*UserWithRoles) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{39}
}

func (x *UserWithRoles) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserWithRoles) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_proto_security_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{40}
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserWithRoles       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_proto_security_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{41}
}

func (x *ListUsersResponse) GetUsers() []*UserWithRoles {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_proto_security_proto protoreflect.FileDescriptor

const file_proto_security_proto_rawDesc = "" +
	"\n" +
	"\x14proto/security.proto\x12\bsecurity\"j\n" +
	"\n" +
	"Permission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"g\n" +
	"\x17CreatePermissionRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"P\n" +
	"\x18CreatePermissionResponse\x124\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2\x14.security.PermissionR\n" +
	"permission\"&\n" +
	"\x14GetPermissionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"M\n" +
	"\x15GetPermissionResponse\x124\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2\x14.security.PermissionR\n" +
	"permission\"w\n" +
	"\x17UpdatePermissionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"P\n" +
	"\x18UpdatePermissionResponse\x124\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2\x14.security.PermissionR\n" +
	"permission\")\n" +
	"\x17DeletePermissionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x18DeletePermissionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x18\n" +
	"\x16ListPermissionsRequest\"Q\n" +
	"\x17ListPermissionsResponse\x126\n" +
	"\vpermissions\x18\x01 \x03(\v2\x14.security.PermissionR\vpermissions\"*\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"q\n" +
	"\x13RoleWithPermissions\x12\"\n" +
	"\x04role\x18\x01 \x01(\v2\x0e.security.RoleR\x04role\x126\n" +
	"\vpermissions\x18\x02 \x03(\v2\x14.security.PermissionR\vpermissions\"I\n" +
	"\x11CreateRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\"G\n" +
	"\x12CreateRoleResponse\x121\n" +
	"\x04role\x18\x01 \x01(\v2\x1d.security.RoleWithPermissionsR\x04role\" \n" +
	"\x0eGetRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x0fGetRoleResponse\x121\n" +
	"\x04role\x18\x01 \x01(\v2\x1d.security.RoleWithPermissionsR\x04role\"Y\n" +
	"\x11UpdateRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vpermissions\x18\x03 \x03(\tR\vpermissions\"G\n" +
	"\x12UpdateRoleResponse\x121\n" +
	"\x04role\x18\x01 \x01(\v2\x1d.security.RoleWithPermissionsR\x04role\"#\n" +
	"\x11DeleteRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteRoleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x12\n" +
	"\x10ListRolesRequest\"H\n" +
	"\x11ListRolesResponse\x123\n" +
	"\x05roles\x18\x01 \x03(\v2\x1d.security.RoleWithPermissionsR\x05roles\",\n" +
	"\x1aListRolePermissionsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"U\n" +
	"\x1bListRolePermissionsResponse\x126\n" +
	"\vpermissions\x18\x01 \x03(\v2\x14.security.PermissionR\vpermissions\"M\n" +
	"\x19SetRolePermissionsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\"6\n" +
	"\x1aSetRolePermissionsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"K\n" +
	"\x15AddUsersToRoleRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\tR\auserIds\"2\n" +
	"\x16AddUsersToRoleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"P\n" +
	"\x1aRemoveUsersFromRoleRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\tR\auserIds\"7\n" +
	"\x1bRemoveUsersFromRoleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"2\n" +
	"\x17ListUsersForRoleRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\"5\n" +
	"\x18ListUsersForRoleResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"L\n" +
	"\x16SetRolesForUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\brole_ids\x18\x02 \x03(\tR\aroleIds\"3\n" +
	"\x17SetRolesForUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"2\n" +
	"\x17ListRolesForUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"@\n" +
	"\x18ListRolesForUserResponse\x12$\n" +
	"\x05roles\x18\x01 \x03(\v2\x0e.security.RoleR\x05roles\"A\n" +
	"&ListRolesWithPermissionsForUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"^\n" +
	"'ListRolesWithPermissionsForUserResponse\x123\n" +
	"\x05roles\x18\x01 \x03(\v2\x1d.security.RoleWithPermissionsR\x05roles\"N\n" +
	"\rUserWithRoles\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\x05roles\x18\x02 \x03(\v2\x0e.security.RoleR\x05roles\"\x12\n" +
	"\x10ListUsersRequest\"B\n" +
	"\x11ListUsersResponse\x12-\n" +
	"\x05users\x18\x01 \x03(\v2\x17.security.UserWithRolesR\x05users2\x88\r\n" +
	"\x0fSecurityService\x12Y\n" +
	"\x10CreatePermission\x12!.security.CreatePermissionRequest\x1a\".security.CreatePermissionResponse\x12P\n" +
	"\rGetPermission\x12\x1e.security.GetPermissionRequest\x1a\x1f.security.GetPermissionResponse\x12Y\n" +
	"\x10UpdatePermission\x12!.security.UpdatePermissionRequest\x1a\".security.UpdatePermissionResponse\x12Y\n" +
	"\x10DeletePermission\x12!.security.DeletePermissionRequest\x1a\".security.DeletePermissionResponse\x12V\n" +
	"\x0fListPermissions\x12 .security.ListPermissionsRequest\x1a!.security.ListPermissionsResponse\x12G\n" +
	"\n" +
	"CreateRole\x12\x1b.security.CreateRoleRequest\x1a\x1c.security.CreateRoleResponse\x12>\n" +
	"\aGetRole\x12\x18.security.GetRoleRequest\x1a\x19.security.GetRoleResponse\x12G\n" +
	"\n" +
	"UpdateRole\x12\x1b.security.UpdateRoleRequest\x1a\x1c.security.UpdateRoleResponse\x12G\n" +
	"\n" +
	"DeleteRole\x12\x1b.security.DeleteRoleRequest\x1a\x1c.security.DeleteRoleResponse\x12D\n" +
	"\tListRoles\x12\x1a.security.ListRolesRequest\x1a\x1b.security.ListRolesResponse\x12b\n" +
	"\x13ListRolePermissions\x12$.security.ListRolePermissionsRequest\x1a%.security.ListRolePermissionsResponse\x12_\n" +
	"\x12SetRolePermissions\x12#.security.SetRolePermissionsRequest\x1a$.security.SetRolePermissionsResponse\x12S\n" +
	"\x0eAddUsersToRole\x12\x1f.security.AddUsersToRoleRequest\x1a .security.AddUsersToRoleResponse\x12b\n" +
	"\x13RemoveUsersFromRole\x12$.security.RemoveUsersFromRoleRequest\x1a%.security.RemoveUsersFromRoleResponse\x12Y\n" +
	"\x10ListUsersForRole\x12!.security.ListUsersForRoleRequest\x1a\".security.ListUsersForRoleResponse\x12V\n" +
	"\x0fSetRolesForUser\x12 .security.SetRolesForUserRequest\x1a!.security.SetRolesForUserResponse\x12Y\n" +
	"\x10ListRolesForUser\x12!.security.ListRolesForUserRequest\x1a\".security.ListRolesForUserResponse\x12\x86\x01\n" +
	"\x1fListRolesWithPermissionsForUser\x120.security.ListRolesWithPermissionsForUserRequest\x1a1.security.ListRolesWithPermissionsForUserResponse\x12D\n" +
	"\tListUsers\x12\x1a.security.ListUsersRequest\x1a\x1b.security.ListUsersResponseB\fZ\n" +
	"./protogenb\x06proto3"

var (
	file_proto_security_proto_rawDescOnce sync.Once
	file_proto_security_proto_rawDescData []byte
)

func file_proto_security_proto_rawDescGZIP() []byte {
	file_proto_security_proto_rawDescOnce.Do(func() {
		file_proto_security_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_security_proto_rawDesc), len(file_proto_security_proto_rawDesc)))
	})
	return file_proto_security_proto_rawDescData
}

var file_proto_security_proto_msgTypes = make([]protoimpl.MessageInfo, 42)
var file_proto_security_proto_goTypes = []any{
	(*Permission)(nil),                              // 0: security.Permission
	(*CreatePermissionRequest)(nil),                 // 1: security.CreatePermissionRequest
	(*CreatePermissionResponse)(nil),                // 2: security.CreatePermissionResponse
	(*GetPermissionRequest)(nil),                    // 3: security.GetPermissionRequest
	(*GetPermissionResponse)(nil),                   // 4: security.GetPermissionResponse
	(*UpdatePermissionRequest)(nil),                 // 5: security.UpdatePermissionRequest
	(*UpdatePermissionResponse)(nil),                // 6: security.UpdatePermissionResponse
	(*DeletePermissionRequest)(nil),                 // 7: security.DeletePermissionRequest
	(*DeletePermissionResponse)(nil),                // 8: security.DeletePermissionResponse
	(*ListPermissionsRequest)(nil),                  // 9: security.ListPermissionsRequest
	(*ListPermissionsResponse)(nil),                 // 10: security.ListPermissionsResponse
	(*Role)(nil),                                    // 11: security.Role
	(*RoleWithPermissions)(nil),                     // 12: security.RoleWithPermissions
	(*CreateRoleRequest)(nil),                       // 13: security.CreateRoleRequest
	(*CreateRoleResponse)(nil),                      // 14: security.CreateRoleResponse
	(*GetRoleRequest)(nil),                          // 15: security.GetRoleRequest
	(*GetRoleResponse)(nil),                         // 16: security.GetRoleResponse
	(*UpdateRoleRequest)(nil),                       // 17: security.UpdateRoleRequest
	(*UpdateRoleResponse)(nil),                      // 18: security.UpdateRoleResponse
	(*DeleteRoleRequest)(nil),                       // 19: security.DeleteRoleRequest
	(*DeleteRoleResponse)(nil),                      // 20: security.DeleteRoleResponse
	(*ListRolesRequest)(nil),                        // 21: security.ListRolesRequest
	(*ListRolesResponse)(nil),                       // 22: security.ListRolesResponse
	(*ListRolePermissionsRequest)(nil),              // 23: security.ListRolePermissionsRequest
	(*ListRolePermissionsResponse)(nil),             // 24: security.ListRolePermissionsResponse
	(*SetRolePermissionsRequest)(nil),               // 25: security.SetRolePermissionsRequest
	(*SetRolePermissionsResponse)(nil),              // 26: security.SetRolePermissionsResponse
	(*AddUsersToRoleRequest)(nil),                   // 27: security.AddUsersToRoleRequest
	(*AddUsersToRoleResponse)(nil),                  // 28: security.AddUsersToRoleResponse
	(*RemoveUsersFromRoleRequest)(nil),              // 29: security.RemoveUsersFromRoleRequest
	(*RemoveUsersFromRoleResponse)(nil),             // 30: security.RemoveUsersFromRoleResponse
	(*ListUsersForRoleRequest)(nil),                 // 31: security.ListUsersForRoleRequest
	(*ListUsersForRoleResponse)(nil),                // 32: security.ListUsersForRoleResponse
	(*SetRolesForUserRequest)(nil),                  // 33: security.SetRolesForUserRequest
	(*SetRolesForUserResponse)(nil),                 // 34: security.SetRolesForUserResponse
	(*ListRolesForUserRequest)(nil),                 // 35: security.ListRolesForUserRequest
	(*ListRolesForUserResponse)(nil),                // 36: security.ListRolesForUserResponse
	(*ListRolesWithPermissionsForUserRequest)(nil),  // 37: security.ListRolesWithPermissionsForUserRequest
	(*ListRolesWithPermissionsForUserResponse)(nil), // 38: security.ListRolesWithPermissionsForUserResponse
	(*UserWithRoles)(nil),                           // 39: security.UserWithRoles
	(*ListUsersRequest)(nil),                        // 40: security.ListUsersRequest
	(*ListUsersResponse)(nil),                       // 41: security.ListUsersResponse
}
var file_proto_security_proto_depIdxs = []int32{
	0,  // 0: security.CreatePermissionResponse.permission:type_name -> security.Permission
	0,  // 1: security.GetPermissionResponse.permission:type_name -> security.Permission
	0,  // 2: security.UpdatePermissionResponse.permission:type_name -> security.Permission
	0,  // 3: security.ListPermissionsResponse.permissions:type_name -> security.Permission
	11, // 4: security.RoleWithPermissions.role:type_name -> security.Role
	0,  // 5: security.RoleWithPermissions.permissions:type_name -> security.Permission
	12, // 6: security.CreateRoleResponse.role:type_name -> security.RoleWithPermissions
	12, // 7: security.GetRoleResponse.role:type_name -> security.RoleWithPermissions
	12, // 8: security.UpdateRoleResponse.role:type_name -> security.RoleWithPermissions
	12, // 9: security.ListRolesResponse.roles:type_name -> security.RoleWithPermissions
	0,  // 10: security.ListRolePermissionsResponse.permissions:type_name -> security.Permission
	11, // 11: security.ListRolesForUserResponse.roles:type_name -> security.Role
	12, // 12: security.ListRolesWithPermissionsForUserResponse.roles:type_name -> security.RoleWithPermissions
	11, // 13: security.UserWithRoles.roles:type_name -> security.Role
	39, // 14: security.ListUsersResponse.users:type_name -> security.UserWithRoles
	1,  // 15: security.SecurityService.CreatePermission:input_type -> security.CreatePermissionRequest
	3,  // 16: security.SecurityService.GetPermission:input_type -> security.GetPermissionRequest
	5,  // 17: security.SecurityService.UpdatePermission:input_type -> security.UpdatePermissionRequest
	7,  // 18: security.SecurityService.DeletePermission:input_type -> security.DeletePermissionRequest
	9,  // 19: security.SecurityService.ListPermissions:input_type -> security.ListPermissionsRequest
	13, // 20: security.SecurityService.CreateRole:input_type -> security.CreateRoleRequest
	15, // 21: security.SecurityService.GetRole:input_type -> security.GetRoleRequest
	17, // 22: security.SecurityService.UpdateRole:input_type -> security.UpdateRoleRequest
	19, // 23: security.SecurityService.DeleteRole:input_type -> security.DeleteRoleRequest
	21, // 24: security.SecurityService.ListRoles:input_type -> security.ListRolesRequest
	23, // 25: security.SecurityService.ListRolePermissions:input_type -> security.ListRolePermissionsRequest
	25, // 26: security.SecurityService.SetRolePermissions:input_type -> security.SetRolePermissionsRequest
	27, // 27: security.SecurityService.AddUsersToRole:input_type -> security.AddUsersToRoleRequest
	29, // 28: security.SecurityService.RemoveUsersFromRole:input_type -> security.RemoveUsersFromRoleRequest
	31, // 29: security.SecurityService.ListUsersForRole:input_type -> security.ListUsersForRoleRequest
	33, // 30: security.SecurityService.SetRolesForUser:input_type -> security.SetRolesForUserRequest
	35, // 31: security.SecurityService.ListRolesForUser:input_type -> security.ListRolesForUserRequest
	37, // 32: security.SecurityService.ListRolesWithPermissionsForUser:input_type -> security.ListRolesWithPermissionsForUserRequest
	40, // 33: security.SecurityService.ListUsers:input_type -> security.ListUsersRequest
	2,  // 34: security.SecurityService.CreatePermission:output_type -> security.CreatePermissionResponse
	4,  // 35: security.SecurityService.GetPermission:output_type -> security.GetPermissionResponse
	6,  // 36: security.SecurityService.UpdatePermission:output_type -> security.UpdatePermissionResponse
	8,  // 37: security.SecurityService.DeletePermission:output_type -> security.DeletePermissionResponse
	10, // 38: security.SecurityService.ListPermissions:output_type -> security.ListPermissionsResponse
	14, // 39: security.SecurityService.CreateRole:output_type -> security.CreateRoleResponse
	16, // 40: security.SecurityService.GetRole:output_type -> security.GetRoleResponse
	18, // 41: security.SecurityService.UpdateRole:output_type -> security.UpdateRoleResponse
	20, // 42: security.SecurityService.DeleteRole:output_type -> security.DeleteRoleResponse
	22, // 43: security.SecurityService.ListRoles:output_type -> security.ListRolesResponse
	24, // 44: security.SecurityService.ListRolePermissions:output_type -> security.ListRolePermissionsResponse
	26, // 45: security.SecurityService.SetRolePermissions:output_type -> security.SetRolePermissionsResponse
	28, // 46: security.SecurityService.AddUsersToRole:output_type -> security.AddUsersToRoleResponse
	30, // 47: security.SecurityService.RemoveUsersFromRole:output_type -> security.RemoveUsersFromRoleResponse
	32, // 48: security.SecurityService.ListUsersForRole:output_type -> security.ListUsersForRoleResponse
	34, // 49: security.SecurityService.SetRolesForUser:output_type -> security.SetRolesForUserResponse
	36, // 50: security.SecurityService.ListRolesForUser:output_type -> security.ListRolesForUserResponse
	38, // 51: security.SecurityService.ListRolesWithPermissionsForUser:output_type -> security.ListRolesWithPermissionsForUserResponse
	41, // 52: security.SecurityService.ListUsers:output_type -> security.ListUsersResponse
	34, // [34:53] is the sub-list for method output_type
	15, // [15:34] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_security_proto_init() }
func file_proto_security_proto_init() {
	if File_proto_security_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_security_proto_rawDesc), len(file_proto_security_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   42,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_security_proto_goTypes,
		DependencyIndexes: file_proto_security_proto_depIdxs,
		MessageInfos:      file_proto_security_proto_msgTypes,
	}.Build()
	File_proto_security_proto = out.File
	file_proto_security_proto_goTypes = nil
	file_proto_security_proto_depIdxs = nil
}
