// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/transaction.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TransactionType enum
type TransactionType int32

const (
	TransactionType_TRANSACTION_TYPE_UNSPECIFIED TransactionType = 0
	TransactionType_BUY                          TransactionType = 1
	TransactionType_SELL                         TransactionType = 2
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "TRANSACTION_TYPE_UNSPECIFIED",
		1: "BUY",
		2: "SELL",
	}
	TransactionType_value = map[string]int32{
		"TRANSACTION_TYPE_UNSPECIFIED": 0,
		"BUY":                          1,
		"SELL":                         2,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_transaction_proto_enumTypes[0].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_proto_transaction_proto_enumTypes[0]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0}
}

// Request message for creating a transaction
type CreateTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BrokerId        string                 `protobuf:"bytes,2,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
	Date            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	TransactionType TransactionType        `protobuf:"varint,4,opt,name=transaction_type,json=transactionType,proto3,enum=transaction.TransactionType" json:"transaction_type,omitempty"`
	Asset           string                 `protobuf:"bytes,5,opt,name=asset,proto3" json:"asset,omitempty"`
	Quantity        float64                `protobuf:"fixed64,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price           float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	Fee             float64                `protobuf:"fixed64,8,opt,name=fee,proto3" json:"fee,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_proto_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTransactionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateTransactionRequest) GetBrokerId() string {
	if x != nil {
		return x.BrokerId
	}
	return ""
}

func (x *CreateTransactionRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *CreateTransactionRequest) GetTransactionType() TransactionType {
	if x != nil {
		return x.TransactionType
	}
	return TransactionType_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *CreateTransactionRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *CreateTransactionRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateTransactionRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateTransactionRequest) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

// Response message for creating a transaction
type CreateTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionResponse) Reset() {
	*x = CreateTransactionResponse{}
	mi := &file_proto_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionResponse) ProtoMessage() {}

func (x *CreateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionResponse.ProtoReflect.Descriptor instead.
func (*CreateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// Request message for retrieving a transaction
type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_proto_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *GetTransactionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

// Response message for retrieving a transaction
type GetTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	mi := &file_proto_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *GetTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// Request message for updating a transaction
type UpdateTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BrokerId        string                 `protobuf:"bytes,3,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
	Date            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	TransactionType TransactionType        `protobuf:"varint,5,opt,name=transaction_type,json=transactionType,proto3,enum=transaction.TransactionType" json:"transaction_type,omitempty"`
	Asset           string                 `protobuf:"bytes,6,opt,name=asset,proto3" json:"asset,omitempty"`
	Quantity        float64                `protobuf:"fixed64,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price           float64                `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`
	Fee             float64                `protobuf:"fixed64,9,opt,name=fee,proto3" json:"fee,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateTransactionRequest) Reset() {
	*x = UpdateTransactionRequest{}
	mi := &file_proto_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransactionRequest) ProtoMessage() {}

func (x *UpdateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransactionRequest.ProtoReflect.Descriptor instead.
func (*UpdateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTransactionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *UpdateTransactionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateTransactionRequest) GetBrokerId() string {
	if x != nil {
		return x.BrokerId
	}
	return ""
}

func (x *UpdateTransactionRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *UpdateTransactionRequest) GetTransactionType() TransactionType {
	if x != nil {
		return x.TransactionType
	}
	return TransactionType_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *UpdateTransactionRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *UpdateTransactionRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *UpdateTransactionRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateTransactionRequest) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

// Response message for updating a transaction
type UpdateTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTransactionResponse) Reset() {
	*x = UpdateTransactionResponse{}
	mi := &file_proto_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransactionResponse) ProtoMessage() {}

func (x *UpdateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransactionResponse.ProtoReflect.Descriptor instead.
func (*UpdateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// Request message for deleting a transaction
type DeleteTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransactionRequest) Reset() {
	*x = DeleteTransactionRequest{}
	mi := &file_proto_transaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransactionRequest) ProtoMessage() {}

func (x *DeleteTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransactionRequest.ProtoReflect.Descriptor instead.
func (*DeleteTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTransactionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *DeleteTransactionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Response message for deleting a transaction
type DeleteTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransactionResponse) Reset() {
	*x = DeleteTransactionResponse{}
	mi := &file_proto_transaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransactionResponse) ProtoMessage() {}

func (x *DeleteTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransactionResponse.ProtoReflect.Descriptor instead.
func (*DeleteTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{7}
}

// Request message for deleting a transaction by broker
type DeleteTransactionByBrokerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrokerId      string                 `protobuf:"bytes,1,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransactionByBrokerRequest) Reset() {
	*x = DeleteTransactionByBrokerRequest{}
	mi := &file_proto_transaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransactionByBrokerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransactionByBrokerRequest) ProtoMessage() {}

func (x *DeleteTransactionByBrokerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransactionByBrokerRequest.ProtoReflect.Descriptor instead.
func (*DeleteTransactionByBrokerRequest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTransactionByBrokerRequest) GetBrokerId() string {
	if x != nil {
		return x.BrokerId
	}
	return ""
}

func (x *DeleteTransactionByBrokerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Response message for deleting a transaction by broker
type DeleteTransactionByBrokerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransactionByBrokerResponse) Reset() {
	*x = DeleteTransactionByBrokerResponse{}
	mi := &file_proto_transaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransactionByBrokerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransactionByBrokerResponse) ProtoMessage() {}

func (x *DeleteTransactionByBrokerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransactionByBrokerResponse.ProtoReflect.Descriptor instead.
func (*DeleteTransactionByBrokerResponse) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{9}
}

// Request message for listing all transactions
type ListTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsRequest) Reset() {
	*x = ListTransactionsRequest{}
	mi := &file_proto_transaction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsRequest) ProtoMessage() {}

func (x *ListTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{10}
}

func (x *ListTransactionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Response message for listing all transactions
type ListTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsResponse) Reset() {
	*x = ListTransactionsResponse{}
	mi := &file_proto_transaction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsResponse) ProtoMessage() {}

func (x *ListTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{11}
}

func (x *ListTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

// Transaction message
type Transaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BrokerId        string                 `protobuf:"bytes,3,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
	Date            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	TransactionType TransactionType        `protobuf:"varint,5,opt,name=transaction_type,json=transactionType,proto3,enum=transaction.TransactionType" json:"transaction_type,omitempty"`
	Asset           string                 `protobuf:"bytes,6,opt,name=asset,proto3" json:"asset,omitempty"`
	Quantity        float64                `protobuf:"fixed64,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price           float64                `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`
	PriceUnit       float64                `protobuf:"fixed64,9,opt,name=price_unit,json=priceUnit,proto3" json:"price_unit,omitempty"`
	Fee             float64                `protobuf:"fixed64,10,opt,name=fee,proto3" json:"fee,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_transaction_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{12}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Transaction) GetBrokerId() string {
	if x != nil {
		return x.BrokerId
	}
	return ""
}

func (x *Transaction) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Transaction) GetTransactionType() TransactionType {
	if x != nil {
		return x.TransactionType
	}
	return TransactionType_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *Transaction) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *Transaction) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Transaction) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Transaction) GetPriceUnit() float64 {
	if x != nil {
		return x.PriceUnit
	}
	return 0
}

func (x *Transaction) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

var File_proto_transaction_proto protoreflect.FileDescriptor

const file_proto_transaction_proto_rawDesc = "" +
	"\n" +
	"\x17proto/transaction.proto\x12\vtransaction\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x02\n" +
	"\x18CreateTransactionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tbroker_id\x18\x02 \x01(\tR\bbrokerId\x12.\n" +
	"\x04date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12G\n" +
	"\x10transaction_type\x18\x04 \x01(\x0e2\x1c.transaction.TransactionTypeR\x0ftransactionType\x12\x14\n" +
	"\x05asset\x18\x05 \x01(\tR\x05asset\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x01R\bquantity\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12\x10\n" +
	"\x03fee\x18\b \x01(\x01R\x03fee\"W\n" +
	"\x19CreateTransactionResponse\x12:\n" +
	"\vtransaction\x18\x01 \x01(\v2\x18.transaction.TransactionR\vtransaction\">\n" +
	"\x15GetTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"T\n" +
	"\x16GetTransactionResponse\x12:\n" +
	"\vtransaction\x18\x01 \x01(\v2\x18.transaction.TransactionR\vtransaction\"\xca\x02\n" +
	"\x18UpdateTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tbroker_id\x18\x03 \x01(\tR\bbrokerId\x12.\n" +
	"\x04date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12G\n" +
	"\x10transaction_type\x18\x05 \x01(\x0e2\x1c.transaction.TransactionTypeR\x0ftransactionType\x12\x14\n" +
	"\x05asset\x18\x06 \x01(\tR\x05asset\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x01R\bquantity\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\x12\x10\n" +
	"\x03fee\x18\t \x01(\x01R\x03fee\"W\n" +
	"\x19UpdateTransactionResponse\x12:\n" +
	"\vtransaction\x18\x01 \x01(\v2\x18.transaction.TransactionR\vtransaction\"Z\n" +
	"\x18DeleteTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x1b\n" +
	"\x19DeleteTransactionResponse\"X\n" +
	" DeleteTransactionByBrokerRequest\x12\x1b\n" +
	"\tbroker_id\x18\x01 \x01(\tR\bbrokerId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"#\n" +
	"!DeleteTransactionByBrokerResponse\"2\n" +
	"\x17ListTransactionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"X\n" +
	"\x18ListTransactionsResponse\x12<\n" +
	"\ftransactions\x18\x01 \x03(\v2\x18.transaction.TransactionR\ftransactions\"\xc5\x02\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tbroker_id\x18\x03 \x01(\tR\bbrokerId\x12.\n" +
	"\x04date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12G\n" +
	"\x10transaction_type\x18\x05 \x01(\x0e2\x1c.transaction.TransactionTypeR\x0ftransactionType\x12\x14\n" +
	"\x05asset\x18\x06 \x01(\tR\x05asset\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x01R\bquantity\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\x12\x1d\n" +
	"\n" +
	"price_unit\x18\t \x01(\x01R\tpriceUnit\x12\x10\n" +
	"\x03fee\x18\n" +
	" \x01(\x01R\x03fee*F\n" +
	"\x0fTransactionType\x12 \n" +
	"\x1cTRANSACTION_TYPE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03BUY\x10\x01\x12\b\n" +
	"\x04SELL\x10\x022\xf8\x04\n" +
	"\x12TransactionService\x12b\n" +
	"\x11CreateTransaction\x12%.transaction.CreateTransactionRequest\x1a&.transaction.CreateTransactionResponse\x12Y\n" +
	"\x0eGetTransaction\x12\".transaction.GetTransactionRequest\x1a#.transaction.GetTransactionResponse\x12b\n" +
	"\x11UpdateTransaction\x12%.transaction.UpdateTransactionRequest\x1a&.transaction.UpdateTransactionResponse\x12b\n" +
	"\x11DeleteTransaction\x12%.transaction.DeleteTransactionRequest\x1a&.transaction.DeleteTransactionResponse\x12z\n" +
	"\x19DeleteTransactionByBroker\x12-.transaction.DeleteTransactionByBrokerRequest\x1a..transaction.DeleteTransactionByBrokerResponse\x12_\n" +
	"\x10ListTransactions\x12$.transaction.ListTransactionsRequest\x1a%.transaction.ListTransactionsResponseB\fZ\n" +
	"./protogenb\x06proto3"

var (
	file_proto_transaction_proto_rawDescOnce sync.Once
	file_proto_transaction_proto_rawDescData []byte
)

func file_proto_transaction_proto_rawDescGZIP() []byte {
	file_proto_transaction_proto_rawDescOnce.Do(func() {
		file_proto_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_transaction_proto_rawDesc), len(file_proto_transaction_proto_rawDesc)))
	})
	return file_proto_transaction_proto_rawDescData
}

var file_proto_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_transaction_proto_goTypes = []any{
	(TransactionType)(0),                      // 0: transaction.TransactionType
	(*CreateTransactionRequest)(nil),          // 1: transaction.CreateTransactionRequest
	(*CreateTransactionResponse)(nil),         // 2: transaction.CreateTransactionResponse
	(*GetTransactionRequest)(nil),             // 3: transaction.GetTransactionRequest
	(*GetTransactionResponse)(nil),            // 4: transaction.GetTransactionResponse
	(*UpdateTransactionRequest)(nil),          // 5: transaction.UpdateTransactionRequest
	(*UpdateTransactionResponse)(nil),         // 6: transaction.UpdateTransactionResponse
	(*DeleteTransactionRequest)(nil),          // 7: transaction.DeleteTransactionRequest
	(*DeleteTransactionResponse)(nil),         // 8: transaction.DeleteTransactionResponse
	(*DeleteTransactionByBrokerRequest)(nil),  // 9: transaction.DeleteTransactionByBrokerRequest
	(*DeleteTransactionByBrokerResponse)(nil), // 10: transaction.DeleteTransactionByBrokerResponse
	(*ListTransactionsRequest)(nil),           // 11: transaction.ListTransactionsRequest
	(*ListTransactionsResponse)(nil),          // 12: transaction.ListTransactionsResponse
	(*Transaction)(nil),                       // 13: transaction.Transaction
	(*timestamppb.Timestamp)(nil),             // 14: google.protobuf.Timestamp
}
var file_proto_transaction_proto_depIdxs = []int32{
	14, // 0: transaction.CreateTransactionRequest.date:type_name -> google.protobuf.Timestamp
	0,  // 1: transaction.CreateTransactionRequest.transaction_type:type_name -> transaction.TransactionType
	13, // 2: transaction.CreateTransactionResponse.transaction:type_name -> transaction.Transaction
	13, // 3: transaction.GetTransactionResponse.transaction:type_name -> transaction.Transaction
	14, // 4: transaction.UpdateTransactionRequest.date:type_name -> google.protobuf.Timestamp
	0,  // 5: transaction.UpdateTransactionRequest.transaction_type:type_name -> transaction.TransactionType
	13, // 6: transaction.UpdateTransactionResponse.transaction:type_name -> transaction.Transaction
	13, // 7: transaction.ListTransactionsResponse.transactions:type_name -> transaction.Transaction
	14, // 8: transaction.Transaction.date:type_name -> google.protobuf.Timestamp
	0,  // 9: transaction.Transaction.transaction_type:type_name -> transaction.TransactionType
	1,  // 10: transaction.TransactionService.CreateTransaction:input_type -> transaction.CreateTransactionRequest
	3,  // 11: transaction.TransactionService.GetTransaction:input_type -> transaction.GetTransactionRequest
	5,  // 12: transaction.TransactionService.UpdateTransaction:input_type -> transaction.UpdateTransactionRequest
	7,  // 13: transaction.TransactionService.DeleteTransaction:input_type -> transaction.DeleteTransactionRequest
	9,  // 14: transaction.TransactionService.DeleteTransactionByBroker:input_type -> transaction.DeleteTransactionByBrokerRequest
	11, // 15: transaction.TransactionService.ListTransactions:input_type -> transaction.ListTransactionsRequest
	2,  // 16: transaction.TransactionService.CreateTransaction:output_type -> transaction.CreateTransactionResponse
	4,  // 17: transaction.TransactionService.GetTransaction:output_type -> transaction.GetTransactionResponse
	6,  // 18: transaction.TransactionService.UpdateTransaction:output_type -> transaction.UpdateTransactionResponse
	8,  // 19: transaction.TransactionService.DeleteTransaction:output_type -> transaction.DeleteTransactionResponse
	10, // 20: transaction.TransactionService.DeleteTransactionByBroker:output_type -> transaction.DeleteTransactionByBrokerResponse
	12, // 21: transaction.TransactionService.ListTransactions:output_type -> transaction.ListTransactionsResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_transaction_proto_init() }
func file_proto_transaction_proto_init() {
	if File_proto_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_transaction_proto_rawDesc), len(file_proto_transaction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_transaction_proto_goTypes,
		DependencyIndexes: file_proto_transaction_proto_depIdxs,
		EnumInfos:         file_proto_transaction_proto_enumTypes,
		MessageInfos:      file_proto_transaction_proto_msgTypes,
	}.Build()
	File_proto_transaction_proto = out.File
	file_proto_transaction_proto_goTypes = nil
	file_proto_transaction_proto_depIdxs = nil
}
