// Code generated by MockGen. DO NOT EDIT.
// Source: ../../../../protogen/broker_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=../../../../protogen/broker_grpc.pb.go -destination=../../../../test/mocks/broker_client.go -package=mocks -mock_names=BrokerServiceClient=BrokerServiceClient BrokerServiceClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	protogen "github.com/Zapharaos/fihub-backend/protogen"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// BrokerServiceClient is a mock of BrokerServiceClient interface.
type BrokerServiceClient struct {
	ctrl     *gomock.Controller
	recorder *BrokerServiceClientMockRecorder
	isgomock struct{}
}

// BrokerServiceClientMockRecorder is the mock recorder for BrokerServiceClient.
type BrokerServiceClientMockRecorder struct {
	mock *BrokerServiceClient
}

// NewBrokerServiceClient creates a new mock instance.
func NewBrokerServiceClient(ctrl *gomock.Controller) *BrokerServiceClient {
	mock := &BrokerServiceClient{ctrl: ctrl}
	mock.recorder = &BrokerServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *BrokerServiceClient) EXPECT() *BrokerServiceClientMockRecorder {
	return m.recorder
}

// TODO mocks base method.
func (m *BrokerServiceClient) TODO(ctx context.Context, in *protogen.TodoRequest, opts ...grpc.CallOption) (*protogen.TodoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TODO", varargs...)
	ret0, _ := ret[0].(*protogen.TodoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TODO indicates an expected call of TODO.
func (mr *BrokerServiceClientMockRecorder) TODO(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TODO", reflect.TypeOf((*BrokerServiceClient)(nil).TODO), varargs...)
}

// MockBrokerServiceServer is a mock of BrokerServiceServer interface.
type MockBrokerServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockBrokerServiceServerMockRecorder
	isgomock struct{}
}

// MockBrokerServiceServerMockRecorder is the mock recorder for MockBrokerServiceServer.
type MockBrokerServiceServerMockRecorder struct {
	mock *MockBrokerServiceServer
}

// NewMockBrokerServiceServer creates a new mock instance.
func NewMockBrokerServiceServer(ctrl *gomock.Controller) *MockBrokerServiceServer {
	mock := &MockBrokerServiceServer{ctrl: ctrl}
	mock.recorder = &MockBrokerServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrokerServiceServer) EXPECT() *MockBrokerServiceServerMockRecorder {
	return m.recorder
}

// TODO mocks base method.
func (m *MockBrokerServiceServer) TODO(arg0 context.Context, arg1 *protogen.TodoRequest) (*protogen.TodoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TODO", arg0, arg1)
	ret0, _ := ret[0].(*protogen.TodoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TODO indicates an expected call of TODO.
func (mr *MockBrokerServiceServerMockRecorder) TODO(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TODO", reflect.TypeOf((*MockBrokerServiceServer)(nil).TODO), arg0, arg1)
}

// mustEmbedUnimplementedBrokerServiceServer mocks base method.
func (m *MockBrokerServiceServer) mustEmbedUnimplementedBrokerServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedBrokerServiceServer")
}

// mustEmbedUnimplementedBrokerServiceServer indicates an expected call of mustEmbedUnimplementedBrokerServiceServer.
func (mr *MockBrokerServiceServerMockRecorder) mustEmbedUnimplementedBrokerServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedBrokerServiceServer", reflect.TypeOf((*MockBrokerServiceServer)(nil).mustEmbedUnimplementedBrokerServiceServer))
}

// MockUnsafeBrokerServiceServer is a mock of UnsafeBrokerServiceServer interface.
type MockUnsafeBrokerServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeBrokerServiceServerMockRecorder
	isgomock struct{}
}

// MockUnsafeBrokerServiceServerMockRecorder is the mock recorder for MockUnsafeBrokerServiceServer.
type MockUnsafeBrokerServiceServerMockRecorder struct {
	mock *MockUnsafeBrokerServiceServer
}

// NewMockUnsafeBrokerServiceServer creates a new mock instance.
func NewMockUnsafeBrokerServiceServer(ctrl *gomock.Controller) *MockUnsafeBrokerServiceServer {
	mock := &MockUnsafeBrokerServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeBrokerServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeBrokerServiceServer) EXPECT() *MockUnsafeBrokerServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedBrokerServiceServer mocks base method.
func (m *MockUnsafeBrokerServiceServer) mustEmbedUnimplementedBrokerServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedBrokerServiceServer")
}

// mustEmbedUnimplementedBrokerServiceServer indicates an expected call of mustEmbedUnimplementedBrokerServiceServer.
func (mr *MockUnsafeBrokerServiceServerMockRecorder) mustEmbedUnimplementedBrokerServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedBrokerServiceServer", reflect.TypeOf((*MockUnsafeBrokerServiceServer)(nil).mustEmbedUnimplementedBrokerServiceServer))
}
