// Code generated by MockGen. DO NOT EDIT.
// Source: utils.go
//
// Generated by this command:
//
//	mockgen -source=utils.go -destination=../../../../test/mocks/handlers_utils.go --package=mocks -mock_names=Utils=MockApiUtils Utils
//

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
	language "golang.org/x/text/language"
)

// MockApiUtils is a mock of Utils interface.
type MockApiUtils struct {
	ctrl     *gomock.Controller
	recorder *MockApiUtilsMockRecorder
	isgomock struct{}
}

// MockApiUtilsMockRecorder is the mock recorder for MockApiUtils.
type MockApiUtilsMockRecorder struct {
	mock *MockApiUtils
}

// NewMockApiUtils creates a new mock instance.
func NewMockApiUtils(ctrl *gomock.Controller) *MockApiUtils {
	mock := &MockApiUtils{ctrl: ctrl}
	mock.recorder = &MockApiUtilsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiUtils) EXPECT() *MockApiUtilsMockRecorder {
	return m.recorder
}

// GetUserIDFromContext mocks base method.
func (m *MockApiUtils) GetUserIDFromContext(r *http.Request) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDFromContext", r)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetUserIDFromContext indicates an expected call of GetUserIDFromContext.
func (mr *MockApiUtilsMockRecorder) GetUserIDFromContext(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDFromContext", reflect.TypeOf((*MockApiUtils)(nil).GetUserIDFromContext), r)
}

// ParseParamBool mocks base method.
func (m *MockApiUtils) ParseParamBool(w http.ResponseWriter, r *http.Request, key string) (bool, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseParamBool", w, r, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// ParseParamBool indicates an expected call of ParseParamBool.
func (mr *MockApiUtilsMockRecorder) ParseParamBool(w, r, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseParamBool", reflect.TypeOf((*MockApiUtils)(nil).ParseParamBool), w, r, key)
}

// ParseParamLanguage mocks base method.
func (m *MockApiUtils) ParseParamLanguage(w http.ResponseWriter, r *http.Request) language.Tag {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseParamLanguage", w, r)
	ret0, _ := ret[0].(language.Tag)
	return ret0
}

// ParseParamLanguage indicates an expected call of ParseParamLanguage.
func (mr *MockApiUtilsMockRecorder) ParseParamLanguage(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseParamLanguage", reflect.TypeOf((*MockApiUtils)(nil).ParseParamLanguage), w, r)
}

// ParseParamString mocks base method.
func (m *MockApiUtils) ParseParamString(w http.ResponseWriter, r *http.Request, key string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseParamString", w, r, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// ParseParamString indicates an expected call of ParseParamString.
func (mr *MockApiUtilsMockRecorder) ParseParamString(w, r, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseParamString", reflect.TypeOf((*MockApiUtils)(nil).ParseParamString), w, r, key)
}

// ParseParamUUID mocks base method.
func (m *MockApiUtils) ParseParamUUID(w http.ResponseWriter, r *http.Request, key string) (uuid.UUID, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseParamUUID", w, r, key)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// ParseParamUUID indicates an expected call of ParseParamUUID.
func (mr *MockApiUtilsMockRecorder) ParseParamUUID(w, r, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseParamUUID", reflect.TypeOf((*MockApiUtils)(nil).ParseParamUUID), w, r, key)
}

// ParseUUIDPair mocks base method.
func (m *MockApiUtils) ParseUUIDPair(w http.ResponseWriter, r *http.Request, key string) (uuid.UUID, uuid.UUID, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseUUIDPair", w, r, key)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(uuid.UUID)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// ParseUUIDPair indicates an expected call of ParseUUIDPair.
func (mr *MockApiUtilsMockRecorder) ParseUUIDPair(w, r, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseUUIDPair", reflect.TypeOf((*MockApiUtils)(nil).ParseUUIDPair), w, r, key)
}

// ReadImage mocks base method.
func (m *MockApiUtils) ReadImage(w http.ResponseWriter, r *http.Request) ([]byte, string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadImage", w, r)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// ReadImage indicates an expected call of ReadImage.
func (mr *MockApiUtilsMockRecorder) ReadImage(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadImage", reflect.TypeOf((*MockApiUtils)(nil).ReadImage), w, r)
}
