// Code generated by MockGen. DO NOT EDIT.
// Source: permission_repository.go
//
// Generated by this command:
//
//	mockgen -source=permission_repository.go -destination=../../../../test/mocks/security_permission_repository.go --package=mocks -mock_names=PermissionRepository=SecurityPermissionRepository PermissionRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/Zapharaos/fihub-backend/internal/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// SecurityPermissionRepository is a mock of PermissionRepository interface.
type SecurityPermissionRepository struct {
	ctrl     *gomock.Controller
	recorder *SecurityPermissionRepositoryMockRecorder
	isgomock struct{}
}

// SecurityPermissionRepositoryMockRecorder is the mock recorder for SecurityPermissionRepository.
type SecurityPermissionRepositoryMockRecorder struct {
	mock *SecurityPermissionRepository
}

// NewSecurityPermissionRepository creates a new mock instance.
func NewSecurityPermissionRepository(ctrl *gomock.Controller) *SecurityPermissionRepository {
	mock := &SecurityPermissionRepository{ctrl: ctrl}
	mock.recorder = &SecurityPermissionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *SecurityPermissionRepository) EXPECT() *SecurityPermissionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *SecurityPermissionRepository) Create(permission models.Permission) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", permission)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *SecurityPermissionRepositoryMockRecorder) Create(permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*SecurityPermissionRepository)(nil).Create), permission)
}

// Delete mocks base method.
func (m *SecurityPermissionRepository) Delete(uuid uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *SecurityPermissionRepositoryMockRecorder) Delete(uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*SecurityPermissionRepository)(nil).Delete), uuid)
}

// Get mocks base method.
func (m *SecurityPermissionRepository) Get(uuid uuid.UUID) (models.Permission, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", uuid)
	ret0, _ := ret[0].(models.Permission)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *SecurityPermissionRepositoryMockRecorder) Get(uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*SecurityPermissionRepository)(nil).Get), uuid)
}

// GetAll mocks base method.
func (m *SecurityPermissionRepository) GetAll() (models.Permissions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].(models.Permissions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *SecurityPermissionRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*SecurityPermissionRepository)(nil).GetAll))
}

// GetAllByRoleId mocks base method.
func (m *SecurityPermissionRepository) GetAllByRoleId(roleUUID uuid.UUID) (models.Permissions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllByRoleId", roleUUID)
	ret0, _ := ret[0].(models.Permissions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllByRoleId indicates an expected call of GetAllByRoleId.
func (mr *SecurityPermissionRepositoryMockRecorder) GetAllByRoleId(roleUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllByRoleId", reflect.TypeOf((*SecurityPermissionRepository)(nil).GetAllByRoleId), roleUUID)
}

// GetAllForUser mocks base method.
func (m *SecurityPermissionRepository) GetAllForUser(userUUID uuid.UUID) (models.Permissions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllForUser", userUUID)
	ret0, _ := ret[0].(models.Permissions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllForUser indicates an expected call of GetAllForUser.
func (mr *SecurityPermissionRepositoryMockRecorder) GetAllForUser(userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllForUser", reflect.TypeOf((*SecurityPermissionRepository)(nil).GetAllForUser), userUUID)
}

// Update mocks base method.
func (m *SecurityPermissionRepository) Update(permission models.Permission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", permission)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *SecurityPermissionRepositoryMockRecorder) Update(permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*SecurityPermissionRepository)(nil).Update), permission)
}
