// Code generated by MockGen. DO NOT EDIT.
// Source: role_repository.go
//
// Generated by this command:
//
//	mockgen -source=role_repository.go -destination=../../../../test/mocks/user_role_repository.go --package=mocks -mock_names=RoleRepository=UserRoleRepository RoleRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/Zapharaos/fihub-backend/internal/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// UserRoleRepository is a mock of RoleRepository interface.
type UserRoleRepository struct {
	ctrl     *gomock.Controller
	recorder *UserRoleRepositoryMockRecorder
	isgomock struct{}
}

// UserRoleRepositoryMockRecorder is the mock recorder for UserRoleRepository.
type UserRoleRepositoryMockRecorder struct {
	mock *UserRoleRepository
}

// NewUserRoleRepository creates a new mock instance.
func NewUserRoleRepository(ctrl *gomock.Controller) *UserRoleRepository {
	mock := &UserRoleRepository{ctrl: ctrl}
	mock.recorder = &UserRoleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *UserRoleRepository) EXPECT() *UserRoleRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *UserRoleRepository) Create(role models.Role, permissionUUIDs []uuid.UUID) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", role, permissionUUIDs)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *UserRoleRepositoryMockRecorder) Create(role, permissionUUIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*UserRoleRepository)(nil).Create), role, permissionUUIDs)
}

// Delete mocks base method.
func (m *UserRoleRepository) Delete(uuid uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *UserRoleRepositoryMockRecorder) Delete(uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*UserRoleRepository)(nil).Delete), uuid)
}

// Get mocks base method.
func (m *UserRoleRepository) Get(uuid uuid.UUID) (models.Role, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", uuid)
	ret0, _ := ret[0].(models.Role)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *UserRoleRepositoryMockRecorder) Get(uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*UserRoleRepository)(nil).Get), uuid)
}

// GetAll mocks base method.
func (m *UserRoleRepository) GetAll() ([]models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *UserRoleRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*UserRoleRepository)(nil).GetAll))
}

// GetAllWithPermissions mocks base method.
func (m *UserRoleRepository) GetAllWithPermissions() (models.RolesWithPermissions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWithPermissions")
	ret0, _ := ret[0].(models.RolesWithPermissions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWithPermissions indicates an expected call of GetAllWithPermissions.
func (mr *UserRoleRepositoryMockRecorder) GetAllWithPermissions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWithPermissions", reflect.TypeOf((*UserRoleRepository)(nil).GetAllWithPermissions))
}

// GetByName mocks base method.
func (m *UserRoleRepository) GetByName(name string) (models.Role, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", name)
	ret0, _ := ret[0].(models.Role)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByName indicates an expected call of GetByName.
func (mr *UserRoleRepositoryMockRecorder) GetByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*UserRoleRepository)(nil).GetByName), name)
}

// GetRolesByUserId mocks base method.
func (m *UserRoleRepository) GetRolesByUserId(userUUID uuid.UUID) ([]models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRolesByUserId", userUUID)
	ret0, _ := ret[0].([]models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRolesByUserId indicates an expected call of GetRolesByUserId.
func (mr *UserRoleRepositoryMockRecorder) GetRolesByUserId(userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRolesByUserId", reflect.TypeOf((*UserRoleRepository)(nil).GetRolesByUserId), userUUID)
}

// GetWithPermissions mocks base method.
func (m *UserRoleRepository) GetWithPermissions(uuid uuid.UUID) (models.RoleWithPermissions, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithPermissions", uuid)
	ret0, _ := ret[0].(models.RoleWithPermissions)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetWithPermissions indicates an expected call of GetWithPermissions.
func (mr *UserRoleRepositoryMockRecorder) GetWithPermissions(uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithPermissions", reflect.TypeOf((*UserRoleRepository)(nil).GetWithPermissions), uuid)
}

// SetRolePermissions mocks base method.
func (m *UserRoleRepository) SetRolePermissions(roleUUID uuid.UUID, permissionUUIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRolePermissions", roleUUID, permissionUUIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRolePermissions indicates an expected call of SetRolePermissions.
func (mr *UserRoleRepositoryMockRecorder) SetRolePermissions(roleUUID, permissionUUIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRolePermissions", reflect.TypeOf((*UserRoleRepository)(nil).SetRolePermissions), roleUUID, permissionUUIDs)
}

// Update mocks base method.
func (m *UserRoleRepository) Update(role models.Role, permissionUUIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", role, permissionUUIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *UserRoleRepositoryMockRecorder) Update(role, permissionUUIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*UserRoleRepository)(nil).Update), role, permissionUUIDs)
}
