// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=../../../../test/mocks/user_repository.go --package=mocks -mock_names=Repository=UserRepository Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/Zapharaos/fihub-backend/internal/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// UserRepository is a mock of Repository interface.
type UserRepository struct {
	ctrl     *gomock.Controller
	recorder *UserRepositoryMockRecorder
	isgomock struct{}
}

// UserRepositoryMockRecorder is the mock recorder for UserRepository.
type UserRepositoryMockRecorder struct {
	mock *UserRepository
}

// NewUserRepository creates a new mock instance.
func NewUserRepository(ctrl *gomock.Controller) *UserRepository {
	mock := &UserRepository{ctrl: ctrl}
	mock.recorder = &UserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *UserRepository) EXPECT() *UserRepositoryMockRecorder {
	return m.recorder
}

// AddUsersRole mocks base method.
func (m *UserRepository) AddUsersRole(userUUIDs []uuid.UUID, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUsersRole", userUUIDs, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUsersRole indicates an expected call of AddUsersRole.
func (mr *UserRepositoryMockRecorder) AddUsersRole(userUUIDs, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUsersRole", reflect.TypeOf((*UserRepository)(nil).AddUsersRole), userUUIDs, id)
}

// Authenticate mocks base method.
func (m *UserRepository) Authenticate(email, password string) (models.User, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", email, password)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Authenticate indicates an expected call of Authenticate.
func (mr *UserRepositoryMockRecorder) Authenticate(email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*UserRepository)(nil).Authenticate), email, password)
}

// Create mocks base method.
func (m *UserRepository) Create(user models.UserWithPassword) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", user)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *UserRepositoryMockRecorder) Create(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*UserRepository)(nil).Create), user)
}

// Delete mocks base method.
func (m *UserRepository) Delete(userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *UserRepositoryMockRecorder) Delete(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*UserRepository)(nil).Delete), userID)
}

// Exists mocks base method.
func (m *UserRepository) Exists(email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *UserRepositoryMockRecorder) Exists(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*UserRepository)(nil).Exists), email)
}

// Get mocks base method.
func (m *UserRepository) Get(userID uuid.UUID) (models.User, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", userID)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *UserRepositoryMockRecorder) Get(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*UserRepository)(nil).Get), userID)
}

// GetAllWithRoles mocks base method.
func (m *UserRepository) GetAllWithRoles() ([]models.UserWithRoles, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWithRoles")
	ret0, _ := ret[0].([]models.UserWithRoles)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWithRoles indicates an expected call of GetAllWithRoles.
func (mr *UserRepositoryMockRecorder) GetAllWithRoles() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWithRoles", reflect.TypeOf((*UserRepository)(nil).GetAllWithRoles))
}

// GetByEmail mocks base method.
func (m *UserRepository) GetByEmail(email string) (models.User, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", email)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *UserRepositoryMockRecorder) GetByEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*UserRepository)(nil).GetByEmail), email)
}

// GetUsersByRoleID mocks base method.
func (m *UserRepository) GetUsersByRoleID(roleUUID uuid.UUID) ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByRoleID", roleUUID)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByRoleID indicates an expected call of GetUsersByRoleID.
func (mr *UserRepositoryMockRecorder) GetUsersByRoleID(roleUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByRoleID", reflect.TypeOf((*UserRepository)(nil).GetUsersByRoleID), roleUUID)
}

// GetWithRoles mocks base method.
func (m *UserRepository) GetWithRoles(userID uuid.UUID) (models.UserWithRoles, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithRoles", userID)
	ret0, _ := ret[0].(models.UserWithRoles)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithRoles indicates an expected call of GetWithRoles.
func (mr *UserRepositoryMockRecorder) GetWithRoles(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithRoles", reflect.TypeOf((*UserRepository)(nil).GetWithRoles), userID)
}

// RemoveUsersRole mocks base method.
func (m *UserRepository) RemoveUsersRole(userUUIDs []uuid.UUID, roleUUID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUsersRole", userUUIDs, roleUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUsersRole indicates an expected call of RemoveUsersRole.
func (mr *UserRepositoryMockRecorder) RemoveUsersRole(userUUIDs, roleUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUsersRole", reflect.TypeOf((*UserRepository)(nil).RemoveUsersRole), userUUIDs, roleUUID)
}

// SetUserRoles mocks base method.
func (m *UserRepository) SetUserRoles(userUUID uuid.UUID, roleUUIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserRoles", userUUID, roleUUIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserRoles indicates an expected call of SetUserRoles.
func (mr *UserRepositoryMockRecorder) SetUserRoles(userUUID, roleUUIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserRoles", reflect.TypeOf((*UserRepository)(nil).SetUserRoles), userUUID, roleUUIDs)
}

// Update mocks base method.
func (m *UserRepository) Update(user models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *UserRepositoryMockRecorder) Update(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*UserRepository)(nil).Update), user)
}

// UpdateWithPassword mocks base method.
func (m *UserRepository) UpdateWithPassword(user models.UserWithPassword) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWithPassword", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWithPassword indicates an expected call of UpdateWithPassword.
func (mr *UserRepositoryMockRecorder) UpdateWithPassword(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWithPassword", reflect.TypeOf((*UserRepository)(nil).UpdateWithPassword), user)
}

// UpdateWithRoles mocks base method.
func (m *UserRepository) UpdateWithRoles(user models.UserWithRoles, roleUUIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWithRoles", user, roleUUIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWithRoles indicates an expected call of UpdateWithRoles.
func (mr *UserRepositoryMockRecorder) UpdateWithRoles(user, roleUUIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWithRoles", reflect.TypeOf((*UserRepository)(nil).UpdateWithRoles), user, roleUUIDs)
}
